### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by heiner** [facebookresearch/moolib#32]
Seems like there's some regression resulting in

```
            obs_future = envs.step(0, action_t)
>           obs = obs_future.result()
E           RuntimeError: Timed out waiting for env

examples/a2c.py:216: RuntimeError
=========================== short test summary info ============================
FAILED test/integration/test_a2c.py::TestA2CExample::test_single_node_training
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
```

See [1](https://github.com/facebookresearch/moolib/runs/5370793867?check_suite_focus=true) and [2](https://github.com/facebookresearch/moolib/runs/5370793959?check_suite_focus=true).

**Comment by tscmoo** [comment]
As nothing changed, any idea what this could be related to?
Did something change in the test environment?

**Comment by heiner** [comment]
What's up? No more changes to this repo in weeks? :(

**Comment by tscmoo** [comment]
Closing as I haven't seen this happen again.
