### ISSUE TITLE
More doc, tutorial, and whitepaper

### ISSUE THREAD

**Issue by LinxiFan** [facebookresearch/moolib#4]
Thank you so much for open-sourcing this library. It looks very useful and interesting. 
Do you have plans to release more docs, tutorials, and/or whitepaper that explains the design choices? 
How does moolib compare to alternative frameworks like Ray or PyTorch RPC, in terms of performance benchmarking and API design?

Many thanks for your help!

**Comment by heiner** [comment]
Thanks for your interest!

More information will be released soon.

**Comment by heiner** [comment]
Hey @LinxiFan,

Thanks again for your interest.

We will release a full whitepaper shortly, but we also host moolib's API docs at https://facebookresearch.github.io/moolib/.

**Comment by LinxiFan** [comment]
Thanks! I look forward to the whitepaper

**Comment by heiner** [comment]
We just pushed the whitepaper to the main branch.
