### ISSUE TITLE
float in pythonserialization.h

### ISSUE THREAD

**Issue by bgyoon** [facebookresearch/moolib#45]
Shouldn't Python float be casted to `double` instead of `float` like 
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/8525211/188565718-6e88351b-5f28-4cb1-b452-045da8adfff0.png">
?

If you run
```
import moolib

def foo(str):
    print(str)
    return 42

host = moolib.Rpc()
host.set_name("host")
host.define("bar", foo)
host.listen("127.0.0.1:1234")

client = moolib.Rpc()
client.connect("127.0.0.1:1234")

print(client.sync("host", "bar", .00002))
```

Output
```
1.9999999494757503e-05
42
```

Expected Output(this is the actual output when `float` is replaced with `double`)
```
2e-05
42
```

**Comment by tscmoo** [comment]
Quite right, thanks!
Happy to accept a PR to fix this.
